# Generated by Django 5.0.6 on 2024-08-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sknne_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimation',
            name='total_votes',
            field=models.FloatField(default=0),
        ),
    ]
