# Generated by Django 5.0.6 on 2024-08-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sknne_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartment',
            name='latitude',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='appartment',
            name='longitude',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='appartment',
            name='place_id',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='city',
            name='zip_code',
            field=models.CharField(default='', max_length=45),
        ),
    ]
