# Generated by Django 5.1 on 2024-08-27 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sknne_app', '0002_appartment_latitude_appartment_longitude_and_more'),
        ('Sknne_app', '0002_estimation_total_votes'),
    ]

    operations = [
    ]
