# Generated by Django 5.0.6 on 2024-08-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sknne_app', '0003_merge_20240827_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartment',
            name='image',
            field=models.ImageField(default=0, upload_to='appartment_images/'),
            preserve_default=False,
        ),
    ]
