# Generated by Django 5.1 on 2024-08-22 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sknne_app', '0003_user_is_active_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
