# Generated by Django 5.1 on 2024-08-23 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sknne_app', '0004_remove_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appartment',
            name='room_description',
        ),
        migrations.RemoveField(
            model_name='estimation',
            name='comment',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
