# Generated by Django 5.1 on 2024-08-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sknne_app', '0004_alter_image_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimation',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
