# Generated by Django 5.0.6 on 2024-08-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sknne_app', '0004_remove_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appartment',
            name='room_description',
        ),
        migrations.RemoveField(
            model_name='estimation',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='estimation',
            name='total_votes',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='rating',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
