# Generated by Django 5.1 on 2024-08-28 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sknne_app', '0005_alter_estimation_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimation',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='estimation',
            name='total_votes',
        ),
        migrations.AddField(
            model_name='appartment',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appartment',
            name='total_votes',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='appartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimation', to='Sknne_app.appartment'),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimation', to='Sknne_app.user'),
        ),
    ]
