# Generated by Django 5.1 on 2024-08-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sknne_app', '0006_remove_estimation_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartment',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
