# Generated by Django 5.1 on 2024-08-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sknne_app', '0007_alter_appartment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartment',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
    ]
