# Generated by Django 5.1 on 2024-08-24 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sknne_app', '0007_remove_appartment_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
