# Generated by Django 5.1 on 2024-08-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sknne_app', '0008_alter_appartment_total_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartment',
            name='total_votes',
            field=models.FloatField(default=0),
        ),
    ]
