# Generated by Django 5.0.6 on 2024-08-28 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sknne_app', '0004_appartment_image'),
        ('Sknne_app', '0009_alter_appartment_total_votes'),
    ]

    operations = [
    ]
