# Generated by Django 5.1 on 2024-08-25 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sknne_app', '0009_alter_appartment_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartment',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appartments', to='Sknne_app.city'),
        ),
    ]
