# Generated by Django 5.1 on 2024-08-26 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sknne_app', '0010_alter_appartment_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimation',
            name='appartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='Sknne_app.appartment'),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='Sknne_app.user'),
        ),
        migrations.AlterField(
            model_name='image',
            name='images',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
