# Generated by Django 5.0.6 on 2024-08-29 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sknne_app', '0010_merge_20240828_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Univirsity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('longitude', models.TextField(default='')),
                ('latitude', models.TextField(default='')),
                ('place_id', models.TextField(default='')),
                ('address', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='Sknne_app.city')),
            ],
        ),
    ]
