# Generated by Django 5.1 on 2024-08-28 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sknne_app', '0010_merge_20240828_2230'),
        ('Sknne_app', '0010_merge_20240828_2301'),
    ]

    operations = [
    ]
